# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n631xCv_VRSW82-WASWGzU8xikS1R5Cc

automate
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
import os

INPUT_PATH = "namadataset_raw/train_df.csv"
OUTPUT_PATH = "preprocessing/namadataset_preprocessing/cleaned_df.csv"

def load_data(path):
    df = pd.read_csv(path)
    return df

def preprocess(df):
    # Handle missing
    df.replace("unknown", pd.NA, inplace=True)
    df = df.dropna()

    # Drop duplicates
    df = df.drop_duplicates()

    # Encoding categorical
    cat_cols = df.select_dtypes(include="object").columns
    df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

    # Scaling
    X = df.drop("berlangganan_deposito", axis=1)
    y = df["berlangganan_deposito"]

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    df_final = pd.DataFrame(X_scaled, columns=X.columns)
    df_final["berlangganan_deposito"] = y.values

    return df_final

def save_data(df):
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    df.to_csv(OUTPUT_PATH, index=False)

if __name__ == "__main__":
    df = load_data(INPUT_PATH)
    df_clean = preprocess(df)
    save_data(df_clean)
    print("✅ Preprocessing selesai. Dataset tersimpan.")